---
resources:
- ../base
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: solver-production
  path: deployment-patch.yaml
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: solver-production
  path: ingress-patch.yaml
- target:
    version: v1
    kind: Service
    name: solver-production
  path: service-patch.yaml
