name: Build Push to Amazon ECR

on:
  push:
    branches:
      - release-preproduction
jobs:
  deploy:
    uses: eco/workflows/.github/workflows/deploy-to-eks.yml@v20231102
    with:
      appname: solver-preproduction
      assumed-role: arn:aws:iam::165381489880:role/solver-eks-actions-beam-production
      aws-region: us-east-2
      ecr-repository: eco-solver
      ghenv: production
      ghsha: 42c3f7509257e4f3aa6961daa5a633564c3bc8a9
      targetenv: preproduction
